name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
tag-prefix: "v"
version-resolver:
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
  $CONTRIBUTORS
 
