name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
tag-prefix: "v"
prerelease: true
version-resolver:
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  $CHANGES
  $CONTRIBUTORS
 
