
name: ezMigrate Stage Environment Build-&-Deploy

on:
  workflow_dispatch:
  
permissions: write-all

env:
  JAVA_VERSION: "8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Show current directory and files
        run: |
          pwd
          ls -l
