
name: ezMigrate Stage Environment Build-&-Deploy

on:
  workflow_dispatch:

permissions: write-all

env:
  JAVA_VERSION: "8"

jobs:
  create-release-tag:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Calculate next tag
        uses: actions/github-script@v6
        id: versioning
        with:
          script: |
           const semver = require('semver');
           const tags = await github.rest.repos.listTags({
           owner: context.repo.owner,
           repo: context.repo.repo,
           per_page: 1,
           });
           const current = tags.data[0]?.name || 'v0.0.0';
           const next = semver.inc(current, 'patch');
           core.info(`Current tag: ${current}`);
           core.info(`Next tag: ${next}`);
           core.setOutput("current", current);
           core.setOutput("next", next);
           
      - name: Next Github tag version
        run: echo "Resolved tag--> ${{ steps.versioning.outputs.next }}"     
          
      - name: Create tag and release
        id: create_release
        uses: ncipollo/release-action@v1.14.0
        with:
          tag: ${{ steps.versioning.outputs.next }}
          name: ${{ steps.versioning.outputs.next }}
          prerelease: true
          generateReleaseNotes: true
          token: ${{ secrets.GH_TOKEN }}

      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.versioning.outputs.next }}"
          echo "Got release version ${{ steps.versioning.outputs.next }}"
          echo "RELEASE_TAG in create-release-tag job: ${{ steps.versioning.outputs.next }}"
          echo "Release upload URL: ${{ steps.create_release.outputs.upload_url }}"
          echo "Release output:"
          echo "${{ toJson(steps.create_release.outputs) }}"
          for key in $(echo "${{ toJson(steps.create_release.outputs) }}" | jq -r "keys_unsorted[]"); do
            value=$(echo "${{ toJson(steps.create_release.outputs) }}" | jq -r ".$key")
            echo "$key: $value"
          done

    outputs:
      LATEST_RELEASE_VERSION: ${{ steps.versioning.outputs.next }}
      UPLOAD_URL: ${{ steps.create_release.outputs.upload_url }}
  build:
    runs-on: ubuntu-latest
    needs: create-release-tag
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Get Commit Short Hash
        id: hash
        run: echo "hash=$(git rev-parse --short \"$RELEVANT_SHA\")" >> $GITHUB_OUTPUT
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Get Latest tag
        id: current_tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Get next minor version
        id: next_tag
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.current_tag.outputs.tag }}

      - name: Use Node.js 22.14.0
        uses: actions/setup-node@v3
        with:
          node-version: "22.14.0"

      - name: Build Angular Integration web app for Production 
        run: |
          npm install
          npm run build:prod
          pwd
          ls -ltr
          mv dist/demo-angular-app/browser/* dist/demo-angular-app
          rm -rf dist/demo-angular-app/browser
          ls -ltr dist/
          echo "Released ${{ steps.next_tag.outputs.patch }} Build - Prod" > ./dist/demo-angular-app/ReleaseVersion.txt
          
      - name: Upload ezMigrate Prod Zip Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ezMigrate-prod-release-${{ steps.date.outputs.date }}
          path: |
            ./dist/
            
      - name: Archive ezMigrate UI QA Build
        uses: vimtor/action-zip@v1
        with:
          files: "./dist/"
          recursive: true
          dest: "ezMigrate-prod-release-${{ steps.date.outputs.date }}.zip"      

      - name: Build Angular Integration web app for QA 
        run: |
          npm install
          npm run build:qa
          pwd
          ls -ltr
          mv dist/demo-angular-app/browser/* dist/demo-angular-app
          rm -rf dist/demo-angular-app/browser
          ls -ltr dist/
          echo "Released ${{ steps.next_tag.outputs.patch }} Build - QA" > ./dist/demo-angular-app/ReleaseVersion.txt
          
      - name: Upload ezMigrate QA Zip Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ezMigrate-qa-release-${{ steps.date.outputs.date }}
          path: |
            ./dist/
            
      - name: Archive ezMigrate UI QA Build
        uses: vimtor/action-zip@v1
        with:
          files: "./dist/"
          recursive: true
          dest: "ezMigrate-qa-release-${{ steps.date.outputs.date }}.zip"     
            
       # Upload Release Asset
      - name: Upload Prod ZIP Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
         upload_url: ${{ needs.create-release-tag.outputs.UPLOAD_URL }}
         asset_path: ./ezMigrate-prod-release-${{ steps.date.outputs.date }}.zip
         asset_name: ezMigrate-prod-release-${{ steps.date.outputs.date }}.zip
         asset_content_type: application/zip
         
      - name: Upload QA ZIP Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
         upload_url: ${{ needs.create-release-tag.outputs.UPLOAD_URL }}
         asset_path: ./ezMigrate-qa-release-${{ steps.date.outputs.date }}.zip
         asset_name: ezMigrate-qa-release-${{ steps.date.outputs.date }}.zip
         asset_content_type: application/zip
