name: DemoWorkflow2
on:
  push:
    branches: [main]
  workflow_dispatch:  
jobs:
  Demojob:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: First Step 1
        uses: actions/checkout@v2
      - name: Second Step 2
        env:
          AZURE_UCAASACS_CONNECTION_STRING: ${{ secrets.AZURE_UCAASACS_CONNECTION_STRING }}
        run: |
           echo ${{ secrets.AZURE_UCAASACS_CONNECTION_STRING }}
      - name: Third Step 3
        env:
          AZURE_UCAASACS_APPLICATION_ID: ${{ secrets.AZURE_UCAASACS_APPLICATION_ID }}
        run: |
           echo ${{ secrets.AZURE_UCAASACS_APPLICATION_ID }}    
