name: Redeploy to Secondary Azure Storage

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        description: 'Run ID of the build workflow'
        required: true

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact from Workflow 1
        uses: actions/download-artifact@v4
        with:
          name: angular-dist
          path: dist/

      - name: Deploy to Secondary Azure Storage
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az storage blob upload-batch \
              --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_2 }} \
              --account-key ${{ secrets.AZURE_STORAGE_KEY_2 }} \
              --source ./dist \
              --destination \$web
