
name: ezMigrate Stage Environment Build-&-Deploy

on:
  workflow_dispatch:

permissions: write-all

env:
  JAVA_VERSION: "8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Get Latest tag
        id: current_tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"	
      
      - name: "Get next minor version"
        id: next_tag
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.current_tag.outputs.tag }}
          
      - name: Check Output Parameters
        run: |
          echo "Got tag name ${{ steps.next_tag.outputs}}"
          echo "Date is ${{steps.date.outputs.date}}"
