name: DemoWorkflow2
on:
  push:
    branches: [main]
  workflow_dispatch:  
jobs:
  Demojob:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: First Step 1
        run: echo "Hi there..."
      - name: Second Step 2
        run: echo "${{ github.ref }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ github.run_number }}
          release_name: v${{ github.event.release.tag_name }}
          body: |
            gh release create ${{ github.ref }} --generate-notes
          draft: false
          prerelease: false
         
