# Workflow to acquire release and deploy to Azure cloud the License Server components
name: ezMigrate to prod release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version (use tags/vxx.xx.xx format)"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Retrieve ezMigrate Production Release ZIP
        id: release_download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: "${{ github.event.inputs.release_version }}"  # Or hardcode a version like "latest"
          regex: true
          file: "ezMigrate-prod-release-.*\\.zip"
          target: "./"

      - name: Unzip ezMigrate prod release build
        run: unzip -qq ezMigrate-prod-release-*.zip -d ./

      - name: Check the folder contents
        run: |
          pwd
          ls -ltr
          ls -ltr ./demo-angular-app
          mv demo-angular-app demo-angular
          ls -ltr
