name: Push Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release Version (use tag:- vxx.xx.xx format)"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION_INPUT: ${{ github.event.inputs.release_version }}

    steps:
      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Get Latest Tag if "latest" is selected
        id: resolve_tag
        uses: actions/github-script@v6
        with:
          script: |
            let versionInput = "${{ env.RELEASE_VERSION_INPUT }}";
            if (versionInput === "latest") {
            const tags = await github.rest.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
            });
            core.info(`GitHub response: ${JSON.stringify(tags, null, 2)}`);
            const latestTag = tags.data[0]?.name;
            if (!latestTag) {
            throw new Error("No tags found in the repository.");
            }
            core.setOutput("tag", latestTag);
            } else {
            core.setOutput("tag", versionInput);
            }

      - name: Debug final tag
        run: echo "Resolved tag--> ${{ steps.resolve_tag.outputs.tag }}"
