name: Push Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Input tag version (input-tag format:- vxx.xx.xx)"
        required: true
        default: "latest"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION_INPUT: ${{ github.event.inputs.release_version }}

    steps:
      - name: Install Zip
        uses: montudor/action-zip@v1

      - name: Get Latest Tag if "latest" is selected
        id: resolve_tag
        uses: actions/github-script@v6
        with:
          script: |
            let versionInput = "${{ env.RELEASE_VERSION_INPUT }}";
            if (versionInput === "latest") {
            const tags = await github.rest.repos.listTags({
            owner: context.repo.owner,
            repo: context.repo.repo,
            per_page: 1
            });
            const latestTag = tags.data[0]?.name;
            if (!latestTag) {
            throw new Error("No tags found in the repository.");
            }
            core.setOutput("tag", latestTag);
            } else {
            core.setOutput("tag", versionInput);
            }

      - name: Debug final tag
        run: echo "Resolved tag--> ${{ steps.resolve_tag.outputs.tag }}"

      - name: Retrieve ezMigrate Production Release ZIP
        id: release_download
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: tags/${{ steps.resolve_tag.outputs.tag }}
          regex: true
          file: "ezMigrate-prod-release-.*\\.zip"
          target: "./"

      - name: Unzip ezMigrate prod release build
        run: unzip -qq ezMigrate-prod-release-*.zip -d ./

      - name: Check the folder contents
        run: |
          pwd
          ls -ltr
          ls -ltr ./demo-angular-app
          mv demo-angular-app demo-angular
          ls -ltr
