name: DemoWorkflow345456
on:
  push:
    branches: [main]
  workflow_dispatch:  
jobs:
  Demojob:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: First Step 1
        run: echo "Hi there....."
      - name: Second Step 2
        run: echo "${{ github.ref }}"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        # with:
        #   config-name: my-config.yml
        #   disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
