name: DemoWorkflow345456
on:
  push:
    branches: [main]
    tags:
      - v*.*.*
      
  workflow_dispatch:  
jobs:
  Demojob:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: First Step 1
        run: echo "Test Test...."
      - name: Second Step 2
        run: echo "${{ github.ref }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Commit Short Hash
        id: hash
        run: echo "hash=$(git rev-parse --short "$RELEVANT_SHA")" >> $GITHUB_OUTPUT
        env:
          RELEVANT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}    
      - name: Get latest release details
        id: release_details
        uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          latest: true

      - name: Get Latest Release commit hash
        id: get_commit
        uses: actions/github-script@v2.1.0
        with:
          script: |
            return "${{fromJSON(steps.release_details.outputs.assets)[0].name}}".split('-').pop().split('.').shift();
      - name: Create Release Notes from commit history
        id: list_messages
        run: echo ${{steps.get_commit.outputs.result}} Is the ${{steps.hash.outputs.hash}}
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          prerelease: false
          generateReleaseNotes: true
          token: ${{ secrets.GITHUB_TOKEN }}  
