name: DemoWorkflow345456
on:
  push:
    branches: [main]
    tags:
      - v*.*.*
      
  workflow_dispatch:  
jobs:
  Demojob:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: First Step 1
        run: echo "Test Test...."
      - name: Second Step 2
        run: echo "${{ github.ref }}"
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: Release Drafter
        uses: release-drafter/release-drafter@v5.25.0
         with:
            publish: true            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
